 name: CI/CD - Build & Deploy
 on:
 push:
 branches: [ main ]
 workflow_dispatch:
 permissions:
 contents: read
 packages: write
 id-token: write
 env:
 IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/wisecow
 jobs:
 build-and-push:
 runs-on: ubuntu-latest
 steps:-name: Checkout
 uses: actions/checkout@v4-name: Set up QEMU
 uses: docker/setup-qemu-action@v3-name: Set up Docker Buildx
 uses: docker/setup-buildx-action@v3-name: Log in to GHCR
 uses: docker/login-action@v3
 with:
 registry: ghcr.io
 username: ${{ github.actor }}
 password: ${{ secrets.GITHUB_TOKEN }}-name: Build and push
 uses: docker/build-push-action@v5
 with:
 context: .
 push: true
 tags: |
 ${{ env.IMAGE_NAME }}:latest
 ${{ env.IMAGE_NAME }}:${{ github.sha }}
 deploy:
 needs: build-and-push
 runs-on: ubuntu-latest
 if: github.ref == 'refs/heads/main'
 steps:-name: Checkout
 uses: actions/checkout@v4-name: Setup kubectl
 uses: azure/setup-kubectl@v3
 with:
 version: 'latest'-name: Configure kubeconfig (from secret)
 run: |
 echo "$KUBECONFIG_DATA" | base64 --decode > $HOME/.kube/config
 env:
 KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}
 - name: Apply manifests
 run: |
 kubectl apply -R -f k8s/- name: Update deployment image
 run: |
 kubectl set image deployment/wisecow wisecow=$
 {{ env.IMAGE_NAME }}:latest -n default || true- name: Wait for rollout
 run: |
 kubectl rollout status deployment/wisecow -n default --timeout=120s
